# Generated by Django 6.0 on 2026-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_text_answer_question_expected_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SHORT', 'Short Answer')], default='SHORT', max_length=10),
        ),
    ]
