# Generated by Django 6.0 on 2026-01-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected_choice',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
