# Generated by Django 6.0 on 2026-01-05 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_answer_selected_choice_delete_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.CharField(choices=[('math', 'Math'), ('physics', 'Physics')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SHORT', 'Short Answer')], db_index=True, default='SHORT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='core_answer_attempt_045164_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='core_examat_student_76b186_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='core_questi_exam_id_08d02f_idx'),
        ),
    ]
