# Generated by Django 6.0 on 2026-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exam_course_alter_exam_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics')], db_index=True, max_length=20),
        ),
    ]
