# Generated by Django 6.0 on 2026-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.CharField(choices=[('chemistry', 'Chemistry'), ('physics', 'Physics')], max_length=100, null=True),
        ),
    ]
